version: '3.8'

services:
  # Botpress
  botpress:
    image: botpress/server
    container_name: botpress
    restart: always
    user: root
    ports:
      - "3001:3000"
    environment:
      - DATABASE=postgres
      - DATABASE_URL=postgres://botpress_user:Admin%40123@db:5432/botpress
    volumes:
      - ./data:/botpress/data
    depends_on:
      - db
    networks:
      - internal

  # Shared PostgreSQL (hỗ trợ extension vector)
  db:
    image: ankane/pgvector:latest
    container_name: botpress_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  # Init DB - tạo user/db cho Botpress
  db_init:
    image: postgres:14
    depends_on:
      - db
    entrypoint: >
      sh -c "
        sleep 5 &&
        psql -h db -U postgres -c \"CREATE USER botpress_user WITH PASSWORD 'Admin@123';\" &&
        psql -h db -U postgres -c \"CREATE DATABASE botpress OWNER botpress_user;\"
      "
    environment:
      PGPASSWORD: postgres
    networks:
      - internal
    restart: "no"

  # MinIO
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    networks:
      - internal
      
  # MinIO Init - Tạo bucket 'botpress' tự động
  minio_init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin); do sleep 1; done;
      /usr/bin/mc ls myminio/botpress || /usr/bin/mc mb myminio/botpress;
      "
    networks:
      - internal
    restart: "no"


volumes:
  postgres_data:
  minio_data:

networks:
  internal:
    driver: bridge
