variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

build:
  only:
    - main
    - tags
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPOSITORY
  script:
    - docker buildx build --network=host -t $DOCKER_REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_REPOSITORY:$CI_COMMIT_SHORT_SHA

update_git_manifest:
  only:
    - main
    - tags
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache git yq
    - git config --global user.email $GIT_USER_EMAIL
    - git config --global user.name $GIT_USER_NAME
    - git clone $MANIFEST_REPOSITORY_URL manifest
    - cd manifest/charts/$CI_PROJECT_NAME
    - yq -i '.image.repository = "'$DOCKER_REPOSITORY'" | .image.tag = "'$CI_COMMIT_SHORT_SHA'"' values-main.yaml
    - git add values-main.yaml
    - 'git commit -m "feat($CI_PROJECT_NAME): update image tag to $CI_COMMIT_SHORT_SHA"'
    - git push
